mysql: 
  port: 3306
  address: "localhost"
  username: "root"
  password: "123456"
  db: "spirit_war"

log:
  path: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info.log"
  node: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info-node.log"
  level: "debug"

openai:
  apikey: "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"